version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - psql:/var/lib/postgresql/data
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
    - redis-data:/var/lib/redis
volumes:
    psql:
    redis-data: